### ISSUE TITLE
Release a versioned tarball.

### ISSUE THREAD

**Issue by Justinzobel** [MediaBrowser/Emby.Releases#16]

**Comment by Naizugai** [comment]
+1

**Comment by Justinzobel** [comment]
Nothing?

**Comment by LukePulverenti** [comment]
can you be more specific because this repo holds a lot of different things. and you are welcome to help achieve what you're looking for.

**Comment by Naizugai** [comment]
He wants to be able to package it for the Linux distro Solus.
