### ISSUE TITLE
accidentaly.deleted.admin.user

### ISSUE THREAD

**Issue by Aishorjo** [MediaBrowser/Emby.Releases#20]
I.accidentally.deleted.admin.user.and.now.i.cannot.login.to.my.own.server.
I.removed.the.server.and.installed.again.bt.some.how.its.chaching.the.old.system.and.not.leting.me.do.anything.pls.help

**Comment by LukePulverenti** [comment]
Hi, what platform are you running Emby Server on?

**Comment by LukePulverenti** [comment]
Are you still having an issue with this?

**Comment by Aishorjo** [comment]
No I just figured that out

**Comment by LukePulverenti** [comment]
Great, thanks !
