### ISSUE TITLE
Duplicate channels with multiple tuners

### ISSUE THREAD

**Issue by hooray4me** [MediaBrowser/Emby.Releases#21]
Adding multiple tuners results in duplicate channels.

![image](https://user-images.githubusercontent.com/12399138/51504434-95696600-1da6-11e9-8e67-c3ecd0d64f7c.png)
![image](https://user-images.githubusercontent.com/12399138/51504437-99958380-1da6-11e9-98ec-c80a9aec0f1b.png)

**Comment by LukePulverenti** [comment]
Hi, this is currently expected behavior. We plan to expand our channel management features in an upcoming release to allow you to better control this.
