### ISSUE TITLE
Do not `chown` all files in `post-install`

### ISSUE THREAD

**Issue by Saviq** [MediaBrowser/Emby.Releases#23]
The current `post-install` script has an unconditional `chmod -R emby:emby`, which includes all the graphics etc. In my case, with a big library, this means up to 5 minutes spent on chowning files that are already owned by `emby:emby`.

IMO if it is a transition thing, it should be only done once.

**Comment by Saviq** [comment]
FWIW it now takes more than 10 minutes on my install to do an upgrade…
```plain
Unpacking emby-server (4.1.0.17) over (4.1.0.16) ...
Setting up emby-server (4.1.0.17) ...
usermod: no changes
Created symlink /etc/systemd/system/multi-user.target.wants/emby-server.service → /usr/lib/systemd/system/emby-server.service.                                                                                                               
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for ureadahead (0.100.0-20) ...

real    10m48,809s
user    0m8,571s
sys     0m11,105s
```

**Comment by RaymondSchnyder** [comment]
Agree. This is very bad on a large library.

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks.
