### ISSUE TITLE
No FreeBSD asset for 4.1.0.20

### ISSUE THREAD

**Issue by JAAlperin** [MediaBrowser/Emby.Releases#24]
emby-server-freebsd_4.1.0.20_amd64.txz is not in the list.

**Comment by LukePulverenti** [comment]
Betas for BSD are flowing again. Thanks.

**Comment by JAAlperin** [comment]
Thank you Luke.

Appreciate that FreeBSD betas are again available.

Upgraded test server to 4.2.0.5 with DLNA 1.0.14.0.  Problem with Oppo BDP-93 persists (when requesting episodes other than 1 in a season other than 1 the first episode of that season is played in error).

3.5.3.0 continues to work properly.





Regards,

Jeff Alperin

H: 561-666-7789
C: 561-797-9876
