### ISSUE TITLE
arch install missing zip

### ISSUE THREAD

**Issue by marshstihl** [MediaBrowser/Emby.Releases#25]
Failure while downloading https://github.com/MediaBrowser/Emby.Releases/releases/download/4.1.0.20/embyserver-netcore_4.1.0.20.zip

**Comment by LukePulverenti** [comment]
We don't have a beta package for Arch linux. I'm aware there is a third party one, but I don't know enough about it to troubleshoot it.

Instructions for installing the stable release can be found here:
https://emby.media/linux-server.html

Thanks.
