### ISSUE TITLE
Version is not updating in Dashboard after upgrade

### ISSUE THREAD

**Issue by hooray4me** [MediaBrowser/Emby.Releases#28]
After upgrading to 4.1.1.0, the version is not updating in the Dashboard.

![image](https://user-images.githubusercontent.com/12399138/57045425-2a47ef00-6c33-11e9-93ca-17eeeb54bae7.png)

**Comment by LukePulverenti** [comment]
Hi, the 4.1.1 packages have been re-posted to correct this. Please install 4.1.1 again. Thanks.

**Comment by LukePulverenti** [comment]
Hi, the 4.1.1 packages have been re-posted to correct this. Please install 4.1.1 again. Thanks.
