### ISSUE TITLE
End User Experience for FireTv/Stick users

### ISSUE THREAD

**Issue by hooray4me** [MediaBrowser/Emby.Releases#29]
On any major or minor server update, (3.x to 4x. or 4.0.x to 4.1.x) our remote users have to remove their configuration (reset cache and data) and re-enter the server information on fire sticks and fire tvs. Otherwise they are unable to login. This has been the case for the last couple years on emby. I've validated this on several of our emby systems.

**Comment by LukePulverenti** [comment]
Since we've been discussing this with you in the Emby Community, let's keep the conversation in one place. Thanks.
