### ISSUE TITLE
Nvidia Shield TV Randomly crashes

### ISSUE THREAD

**Issue by pbeeler** [MediaBrowser/Emby.Releases#30]
I'm not sure why, but when I reverted back to version 4.0.2.0 release build, everything is great and Rock-solid.  Any newer version causes random crashing.  Not sure what changed from this build to the next that would cause this.  It would be nice to be able to run a newer build eventually.  Thank you for your hard work!

**Comment by LukePulverenti** [comment]
Hi, can you please attach the emby server log? Thanks !

**Comment by pbeeler** [comment]
I just tried version 4.1.1.0 for the first time and it crashes on startup and I looked and there's no logs for it.  I'll try one of the other previous versions and get a lot

**Comment by pbeeler** [comment]
Here are some logs for Verizon 4.1.0.26.  these were all created around the same time so I'm not sure which ones you need.
[embyserver-63693884487.txt](https://github.com/MediaBrowser/Emby.Releases/files/3195768/embyserver-63693884487.txt)
[embyserver.txt](https://github.com/MediaBrowser/Emby.Releases/files/3195769/embyserver.txt)
[hardware_detection-63693884447.txt](https://github.com/MediaBrowser/Emby.Releases/files/3195771/hardware_detection-63693884447.txt)
[hardware_detection-63693884514.txt](https://github.com/MediaBrowser/Emby.Releases/files/3195772/hardware_detection-63693884514.txt)

**Comment by LukePulverenti** [comment]
Can you try removing the cover art plugin, then restarting the server and seeing if that helps? thanks.

**Comment by pbeeler** [comment]
I uninstalled the cover art plugin and 4.1.1.0 still crashes on startup.  4.1.0.26 still crashed randomly when I tried to play a recorded show from my phone remotely on the LAN network.

**Comment by LukePulverenti** [comment]
Can you try removing the dlna and kodi sync plugins and see if that has an impact? Thanks.

**Comment by pbeeler** [comment]
Did they logs not provide you with West you needs?

**Comment by LukePulverenti** [comment]
Unfortunately there's nothing obvious in them so that's why I asked you to try that. But since you've already rolled back we can wait and re-evaluate with the next release. Thanks.

**Comment by pbeeler** [comment]
Thanks I'll test more this week and get back to you on those plugins

**Comment by pbeeler** [comment]
Hi Luke, I tested both of the plugins and it doesn't seem to be the cause of the freezing and crashing.  On all the versions, I get a volley error message that the server can not be accessed.

**Comment by pbeeler** [comment]
I moved my server over to a windows 10 mini pc
