### ISSUE TITLE
4.2.0.7 wont start in FreeBSD 11.2

### ISSUE THREAD

**Issue by Oriann** [MediaBrowser/Emby.Releases#31]
After upgrading from 4.2.0.5 to 4.2.0.7 in FreeBSD 11.2, service emby-server wont start anymore.

Upgrading with this:

service emby-server stop
pkg add -f https://github.com/MediaBrowser/Emby.Releases/releases/download/4.2.0.7/emby-server-freebsd11_4.2.0.7_amd64.txz
service emby-server start

Starting emby-server..

service emby-server status
emby_server is not running

Is there a problem in new release ?

**Comment by LukePulverenti** [comment]
I've re-uploaded it. Can you try again? Thanks.

**Comment by Oriann** [comment]
Hello Luke

I have tried to upgrade with your new package.

Results:
emby-server starts for a while and then shutdown after 3 seconds

All dependencies installed, tried even pkg update /pkg upgrade but all latest packages.

Just for a hint, this happend to me when I was installing syncthing in iocage and syncthing didint have right permissions. Are permissions set correctly in pkg installer ?

**Comment by Oriann** [comment]
New version released
