### ISSUE TITLE
Emby 4.2.0.8. beta - no available streams when click play

### ISSUE THREAD

**Issue by Oriann** [MediaBrowser/Emby.Releases#32]
Today I have researched why new emby version wont play.

Issue: 
After clicking play on any movie, stream wont load and ends with error that no media streams are available.

Solution:
Checking log of ffmpeg-directstream throws this
`Shared object "libvpx.so.6" not found, required by "libavcodec.so.58"`

So in FreeBSD jail I have installed with pkg command library libvpx
`pkg install libvpx`

@LukePulverenti Please add this library on website page with FreeBSD install to direct everyone that they need this for now to get emby work.

**Comment by LukePulverenti** [comment]
Will do, thanks. By the way, I assume this is FireFox? Firefox does not ship with h264 support, so that's why we have to transcode to vp8. You can manually add h264 support to firefox by doing this:
https://support.mozilla.org/en-US/kb/open-h264-plugin-firefox

That will actually get you a better experience. But yes, we'll make the website correction as well. Thanks.

**Comment by Oriann** [comment]
> Will do, thanks. By the way, I assume this is FireFox? Firefox does not ship with h264 support, so that's why we have to transcode to vp8. You can manually add h264 support to firefox by doing this:
> https://support.mozilla.org/en-US/kb/open-h264-plugin-firefox
> 
> That will actually get you a better experience. But yes, we'll make the website correction as well. Thanks.

Nope I am using Chrome ver. 74.0.3729.169 (64-bit).

**Comment by LukePulverenti** [comment]
Ok, then it must be a similar situation because vpx only gets used when the browser doesn't support h264.

**Comment by Oriann** [comment]
On emby ver. 4.2.0.5 it worked in chrome normally without installing this additional library
After upgrading to v4.2.0.8 I needed to manually install vpx.
I think problem is somewhere else not in a browser.

**Comment by LukePulverenti** [comment]
Sorry, my mistake. Vpx is not actually being used in this scenario, however it is now a dependency of the package and will need to be present, so it's just a matter of installing it. We'll get the website updated. Thanks.

**Comment by damelloman24** [comment]
@Oriann  Thank you I had the same issue and this fixed it!  :)

**Comment by kurbly** [comment]
Hi!
I have the same problem. I tried to reinstall libvpx via pkg, and now I'm running libvpx-1.8.1_1 (just like before the reinstall), but the problem persist. I'm running the latest packages, and Emby 4.4.0.2 beta on FreeBSD 12.0

**Comment by LukePulverenti** [comment]
Hi there, please attach the emby server and ffmpeg log. thanks.

**Comment by kurbly** [comment]
Thanks, here are the files

[embyserver.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996491/embyserver.txt)
[ffmpeg-directstream-d6ceaef4-3ac9-40b2-bf83-5fa8ee51c3be_1.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996492/ffmpeg-directstream-d6ceaef4-3ac9-40b2-bf83-5fa8ee51c3be_1.txt)
[embyserver-63712735922.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996493/embyserver-63712735922.txt)

**Comment by LukePulverenti** [comment]
Ok, and I assume you ran the command to install dependencies as mentioned on our website download page? And that your system is configured for latest packages?

**Comment by Oriann** [comment]
> Thanks, here are the files
> 
> [embyserver.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996491/embyserver.txt)
> [ffmpeg-directstream-d6ceaef4-3ac9-40b2-bf83-5fa8ee51c3be_1.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996492/ffmpeg-directstream-d6ceaef4-3ac9-40b2-bf83-5fa8ee51c3be_1.txt)
> [embyserver-63712735922.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996493/embyserver-63712735922.txt)

As I see from logs, your emby server requires another depenedency - libx265.so, maybe you need to install one more package because some dependecies could have nested dependencies. 

Try to install pkg install x265
Or install port from /multimedia/x265

**Comment by kurbly** [comment]
> > Thanks, here are the files
> > [embyserver.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996491/embyserver.txt)
> > [ffmpeg-directstream-d6ceaef4-3ac9-40b2-bf83-5fa8ee51c3be_1.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996492/ffmpeg-directstream-d6ceaef4-3ac9-40b2-bf83-5fa8ee51c3be_1.txt)
> > [embyserver-63712735922.txt](https://github.com/MediaBrowser/Emby.Releases/files/3996493/embyserver-63712735922.txt)
> 
> As I see from logs, your emby server requires another depenedency - libx265.so, maybe you need to install one more package because some dependecies could have nested dependencies.
> 
> Try to install pkg install x265
> Or install port from /multimedia/x265

Thanks for your help, now I could solve the issue.
The new ffmpeg update requires a newer version of x265, which contains the 179th version of libx265.so, but it's not a stable update now, and normally I can only install stable version via pkg. So I deleted it, and reistalled it using ports.
