### ISSUE TITLE
4.2.0.11-beta release incomplete

### ISSUE THREAD

**Issue by thelamer** [MediaBrowser/Emby.Releases#33]
Not sure if this is standard practice but the 4.2.0.11-beta release seems to be incomplete , it is missing a bunch of the files like RPMs etc. 

Do you roll out the files staggered for beta releases?

**Comment by LukePulverenti** [comment]
They are still in process of being built and uploaded. Thanks.

**Comment by LukePulverenti** [comment]
Should be up soon though.

**Comment by thelamer** [comment]
Understood, I was working on an automated ingestion method for new Emby releases. Is there an endpoint that can be used to determine when a release is truly finished being built and all assets are available here ?

**Comment by LukePulverenti** [comment]
Yea I would just use the github api. That is what our website uses to display the available downloads. The key is to check for both the presence of the release, and the actual file within the assets list:
https://emby.media/resources/githubapi_1.js

**Comment by thelamer** [comment]
Thanks for the info
