### ISSUE TITLE
Czech subtitles not encoded correctly

### ISSUE THREAD

**Issue by Oriann** [MediaBrowser/Emby.Releases#34]
Hello @LukePulverenti 

I have problem with sub encoding in movies.
Checked original .srt file and its translated correctly with special characters.
In movie it shows with different characters.
Here example in emby:
![image](https://user-images.githubusercontent.com/11374526/58791000-ba41d580-85f1-11e9-90c6-aa68bf715ef2.png)
Here example in .srt file:
![image](https://user-images.githubusercontent.com/11374526/58791044-cc237880-85f1-11e9-9ff4-e6b4b5dbc41a.png)

Please fix :)

If you need additional info I am ready to provide it.

**Comment by LukePulverenti** [comment]
Is that the web app? Can you zip up sample srt and attach them here? Thanks.

**Comment by Oriann** [comment]
This happens in web app and on Samsung TV app (2017 model)
Here is sample .srt that belong to movie in my 1st post.
[Strach a hnus v Las Vegas (1998).zip](https://github.com/MediaBrowser/Emby.Releases/files/3251088/Strach.a.hnus.v.Las.Vegas.1998.zip)

**Comment by LukePulverenti** [comment]
Your screenshot of the video is exactly how it looks for me in Chrome, and it also looks exactly the same in notepad++.

I assume your screenshot is notepad++, but what I see looks different. 
![Untitled](https://user-images.githubusercontent.com/3607463/58899482-090f6e00-86cb-11e9-9a5a-77c06189af49.png)

**Comment by Oriann** [comment]
So where is the problem then ?
I have tried it on smartphone too but the effect is still same.
I have extracted the zip and tried to open it again but I see it correctly in my language.

**Comment by LukePulverenti** [comment]
Do i need to configure notepad++ somehow to see them differently?

**Comment by Oriann** [comment]
So this settings changes my .srt file to bad characters
![image](https://user-images.githubusercontent.com/11374526/58907986-b4421680-870f-11e9-832a-b6971ee3bea4.png)

And this setting is correct for my language
![image](https://user-images.githubusercontent.com/11374526/58908073-e6ec0f00-870f-11e9-8e54-63d35873823c.png)

**Comment by LukePulverenti** [comment]
That helped, thanks. I was able to resolve it for the next release.

**Comment by Oriann** [comment]
Thank you Luke 👍
