### ISSUE TITLE
Latest beta release missing Linux assets 

### ISSUE THREAD

**Issue by thelamer** [MediaBrowser/Emby.Releases#35]
https://github.com/MediaBrowser/Emby.Releases/releases/tag/4.2.0.16

Is this expected behavior or just something with this specific release. I am trying to hammer out logic downstream and need to know if these types of beta releases are expected so we can bake in a sane failure limit for checks.

**Comment by LukePulverenti** [comment]
They're on the way up. Sometimes they will just run a little behind. If you are writing some kind of update tool, then please make sure it checks the assets list to ensure the file is actually there. Thanks.

**Comment by thelamer** [comment]
We do it is just this one was hanging for 10 hours.
Thanks for the quick response . Will keep logic as is.

**Comment by thelamer** [comment]
I hope you look at Necro issues because I hate to keep filing ones about beta releases. 
The latest beta is missing the x86 and aarch rpms .
