### ISSUE TITLE
Emby keeps accessing shares even when not scheduled to and keeps disks spinning

### ISSUE THREAD

**Issue by ilgrank** [MediaBrowser/Emby.Releases#36]
Hi
I have a Windows pc exposing SMB shares on which I configured to spin down disks since I really watch movies just at night
I've noticed that since installing Emby, the shares get accessed very often, keeping the disks spinning.
I've installed Process Monitor and verified that the Emby process keeps 'exploring' the shares (looking for new/modified content?) even tho I scheduled all the scans to happen at 3 am:
<img width="148" alt="Emby-1" src="https://user-images.githubusercontent.com/4583412/59568596-2a823980-907d-11e9-9f3e-3f444361e57d.PNG">
<img width="625" alt="Emby-2" src="https://user-images.githubusercontent.com/4583412/59568594-29e9a300-907d-11e9-9beb-1d983eb86b01.PNG">
<img width="394" alt="Emby-3" src="https://user-images.githubusercontent.com/4583412/59568595-29e9a300-907d-11e9-90c0-d9b46c5f7597.PNG">
Also, judging from the "Last Run" time, Emby seems to ignore altogether the setting (screenshot taken at 9PM, telling the scan tan 11 hours ago, when the Schedule is on 3AM...)

**Comment by LukePulverenti** [comment]
Hi, try turning off the realtime monitor for each of your emby libraries.

**Comment by ilgrank** [comment]
Checked all the libraries, and it was already turned off for each of them ...
<img width="698" alt="Emby-4" src="https://user-images.githubusercontent.com/4583412/59569253-fad82f00-9086-11e9-9ba5-29326f0d0fe1.PNG">

**Comment by LukePulverenti** [comment]
server log?

**Comment by ilgrank** [comment]
any way I can send it to you privately?

**Comment by LukePulverenti** [comment]
Yes, within the Emby community.
https://emby.media/community

**Comment by ilgrank** [comment]
I tried registering, but I get instabanned

**Comment by LukePulverenti** [comment]
Can you try again? I didn't do anything but I see the forum account you created and it looks like it's in normal member status.

**Comment by LukePulverenti** [comment]
Hi, were you able to try again? Thanks.

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open with the requested information. Thanks.
