### ISSUE TITLE
4.2.0.19 wont start as service on FreeBSD 11.2

### ISSUE THREAD

**Issue by Oriann** [MediaBrowser/Emby.Releases#38]
After upgrading from 4.2.0.17 to 4.2.0.18 in FreeBSD 11.2, service emby-server wont start anymore.

Upgrading with this:

service emby-server stop
pkg add -f https://github.com/MediaBrowser/Emby.Releases/releases/download/4.2.0.18/emby-server-freebsd11_4.2.0.18_amd64.txz
service emby-server start

Starting emby-server..
daemon: process already running, pid: ***

service emby-server status
emby_server is not running

But my emby server is running fine...

**Comment by LukePulverenti** [comment]
Server log? Did you try 4.2.0.19?

**Comment by Oriann** [comment]
Sorry mistyped version, problematic ver is 4.2.0.19, corrected subject.

Log here:
[embyserver.txt](https://github.com/MediaBrowser/Emby.Releases/files/3318371/embyserver.txt)

**Comment by LukePulverenti** [comment]
So the OS thinks it's not running, even though it is?

**Comment by Oriann** [comment]
Correctly.
Starting emby-server just throw message that the daemon is already running but service emby-server status shows its not running.

Interesting...

**Comment by BoldPhoenix** [comment]
The daemon starts automatically, I find myself manually stopping the daemon and starting the service I created. I haven't found a way to disable the daemon. Lol for the little green diamond in the bottom right corner of your taskbar.

**Comment by Oriann** [comment]
But whs is running daemon when I have set up service ? I dont want emby to run as a daemon...

There are other critical services that needs to be ran as daemon.
Also running this kind of app as a daemon is a little security vulnerability isnt it ?

**Comment by LukePulverenti** [comment]
> But whs is running daemon when I have set up service ? I dont want emby to run as a daemon...
> 
> There are other critical services that needs to be ran as daemon.
> Also running this kind of app as a daemon is a little security vulnerability isnt it ?

Hi, a daemon is just a background process, nothing more, nothing less. It has nothing to do with security. Running as root is a security vulnerability, we don't, we run as a dedicated, unprivileged user.

**Comment by Oriann** [comment]
@LukePulverenti so now I dont need to set up service on BSD ? emby is automatically ran as daemon after install ?

**Comment by LukePulverenti** [comment]
@Oriann 
We don't enable and automatically start emby on freebsd, in fact it is forbidden. The service must be enabled in /etc/rc.conf like any other service to be autostarted at boot.

**Comment by Oriann** [comment]
Here is the log from SSH:

`Edit /etc/motd to change this login announcement.
root@emby1:~ # service emby-server status
emby_server is not running.
root@emby1:~ # service emby-server stop
emby_server not running? (check /var/run/emby-server.pid).
root@emby1:~ # service emby-server start
Starting emby_server.
daemon: process already running, pid: 88744
/usr/local/etc/rc.d/emby-server: WARNING: failed to start emby_server
root@emby1:~ #
`
I have never set up a daemon for emby...thats why I am asking why its doing this.
Yesterday I have updated emby 4.2.0.23 and for a while I could control emby_server via service command but today its not possible anymore again...
its like iluminati on my NAS !

**Comment by Oriann** [comment]
Fixed.
