### ISSUE TITLE
Unable to select 240kbps transcoding FireTV 4.2.0.25 server

### ISSUE THREAD

**Issue by BrianSDX2** [MediaBrowser/Emby.Releases#39]
When I try to select 240kbps for max streaming bitrate the app freezes.

**Comment by LukePulverenti** [comment]
Hi, where and when exactly does it freeze? Is this in the app's settings? Or is this in the video player during playback?

**Comment by BrianSDX2** [comment]
In the app settings. Have to force close the app then relaunch.

**Comment by BrianSDX2** [comment]
I should mention, selecting 240kbps during video playback does work. It appears to be just when trying to save that setting in App Settings > Playback > Max Streaming Bitrate

**Comment by ebr11** [comment]
Thanks for the report.  We'll take a look.

**Comment by ebr11** [comment]
This will be fixed in the next release of the app.

Thanks again for bringing it to our attention.  This had been there a while but no one had reported it.
