### ISSUE TITLE
4.2.0.40 wont start from docker image

### ISSUE THREAD

**Issue by Anian-igor** [MediaBrowser/Emby.Releases#41]
Hello.
I've update docker image to last and cannot login to server via web ui
2019-07-26 07:17:40.721 Error HttpServer: Error processing request
<------>*** Error Report ***
<------>Version: 4.2.0.40
<------>Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
<------>Operating system: Unix 4.15.0.54
<------>64-Bit OS: True
<------>64-Bit Process: True
<------>User Interactive: True
<------>Runtime: file:///system/System.Private.CoreLib.dll
<------>Processor count: 2
<------>Program data path: /config
<------>Application directory: /system
<------>System.ArgumentException: System.ArgumentException: netmask
<------>   at System.Net.IPNetwork.InternalParse(Boolean tryParse, ReadOnlySpan`1 ipaddress, ReadOnlySpan`1 netmask, IPNetwork& ipnetwork)
<------>   at System.Net.IPNetwork.InternalParse(Boolean tryParse, ReadOnlySpan`1 network, IPNetwork& ipnetwork)
<------>   at Emby.Server.Implementations.Networking.NetworkManager.IsAddressInSubnets(IPAddress address, ReadOnlySpan`1 addressString, String[] subnets)
<------>   at Emby.Server.Implementations.Networking.NetworkManager.IsInLocalNetworkInternal(ReadOnlyMemory`1 endpoint, Boolean resolveHost, CancellationToken cancellationToken)
<------>   at EmbyServer.SocketSharp.WebSocketSharpRequest.IsInLocalNetwork(CancellationToken cancellationToken)
<------>   at MediaBrowser.Api.UserService.Get(GetUsers request, Boolean filterByDevice, Boolean filterByNetwork, Boolean isAuthenticated, CancellationToken cancellationToken)
<------>   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
<------>   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
<------>   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 host, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
<------>Source: Emby.Server.Implementations
<------>TargetSite: Void InternalParse(Boolean, System.ReadOnlySpan`1[System.Char], System.ReadOnlySpan`1[System.Char], System.Net.IPNetwork ByRef)
<------>
2019-07-26 07:17:40.728 Info HttpServer: HTTP Response 400 to 192.168.10.2. Time: 97ms. http://192.168.248.10:8096/emby/users/public

**Comment by LukePulverenti** [comment]
Hi, can you please attach a copy of this file?
/config/config/system.xml

Thanks.

**Comment by Anian-igor** [comment]
Hi
https://gist.github.com/Anian-igor/0ec023d15fa12eb22c50880e0827cac3

**Comment by Anian-igor** [comment]
I changed <LocalNetworkSubnets> to only one network and server are availible right now.

**Comment by LukePulverenti** [comment]
Hi, what do you mean only one network?

**Comment by Anian-igor** [comment]
Was
 <LocalNetworkSubnets>
    <string>192.168.248.0/24;192.168.10.0/24</string>
Now
  <LocalNetworkSubnets>
    <string>192.168.248.0/24</string>
    <string>192.168.10.0/28</string>
I think that ";" separator was work before and now don't work.

**Comment by LukePulverenti** [comment]
Right, each entry should be on it's own line in the config file. did you edit that by hand?

**Comment by Anian-igor** [comment]
I left only one network by hand. Server was started success. After that I added second network via interface gui.
Server have worked fine now. Thanks.

**Comment by LukePulverenti** [comment]
Thanks for the info. I'm just curious though, did you originally edit it by hand with the ; separator?

**Comment by Anian-igor** [comment]
I added a separator via interface few month ago. But server have a trouble to start only 25.07
Right now I added network with correct separator ","

**Comment by LukePulverenti** [comment]
Ok that's very helpful, thanks. I'll look at it and make sure it can handle both ways.
