### ISSUE TITLE
Explicitly set the playback aspect ratio

### ISSUE THREAD

**Issue by nebulade** [MediaBrowser/Emby.Releases#42]
Hi,

is there a way to explicitly set the aspect ratio during playback? I have some movies which are not correctly played back. VLC also by default has the same, in this case wrong, aspect ratio for those movies, however in VLC I can overwrite that default during playback.

**Comment by LukePulverenti** [comment]
In Emby Server 4.3, the web app has new aspect ratio options.

**Comment by nebulade** [comment]
Ah indeed! I gave it a try now and the three options (auto, cover, fill) I have available work great. Thanks
