### ISSUE TITLE
FreeBSD 12.0 Quarterly Updated After Build

### ISSUE THREAD

**Issue by jed-frey** [MediaBrowser/Emby.Releases#43]
emby-server 4.3.0.5-beta fails to playback on some devices due to a library mismatch on FreeBSD 12.0

[From this thread](https://emby.media/community/index.php?/topic/12906-freebsd-package/page-4) FreeBSD is built against quarterly, not 'latest'. 

It looks like timing was just off as the quarterly packages updated a day after your release package was built.

http://pkg.freebsd.org/FreeBSD:12:amd64/quarterly/All/

Current workaround is to use older package repository:

http://pkg.freebsd.org/FreeBSD:12:amd64/release_0/All/

**Comment by LukePulverenti** [comment]
New betas are up. Thanks for your patience.

**Comment by jed-frey** [comment]
Works great!
