### ISSUE TITLE
Building collections within collections is no more possible

### ISSUE THREAD

**Issue by Haraldos** [MediaBrowser/Emby.Releases#44]

**Comment by LukePulverenti** [comment]
It's not available in the UI due to too many problems and troubleshooting. If you really want, you can hack a collection.xml file to add one collection into another. But we're not going to expose it in the UI until it is bulletproof and just works.

**Comment by LukePulverenti** [comment]
Re:
https://emby.media/community/index.php?/topic/78122-building-collections-within-collections-is-no-more-working
