### ISSUE TITLE
No images being displayed / found

### ISSUE THREAD

**Issue by soupli** [MediaBrowser/Emby.Releases#46]
Hi,

Series are being identified, but no images are being found. Thus no primary images are being displayed:

![Screenshot_20191118-201921](https://user-images.githubusercontent.com/1036817/69083513-87c25280-0a42-11ea-85f6-57bd04aa145e.png)

![Screenshot_20191118-203347](https://user-images.githubusercontent.com/1036817/69083751-0cad6c00-0a43-11ea-9108-8d9754ac1eaf.png)

Am I missing something?

---

Emby 4.3.0.23-beta / Ubuntu server 16.04
Preferred image download language: English
Metadata downloaders are enabled

Thanks!

**Comment by LukePulverenti** [comment]
Hi, just follow along here:
https://emby.media/community/index.php?/topic/79269-tvdb-api-issues/
