### ISSUE TITLE
Release Synology SPK for manual installs

### ISSUE THREAD

**Issue by ShobuPrime** [MediaBrowser/Emby.Releases#47]
I noticed almost every installer Emby supports except for Synology's are released on GitHub.

I was wondering if they could please be considered for future releases as you already release installers for QNAP, for example.

My Synology Package is telling me there's an update and to go to Package Center, but it reports no updates available.

**Comment by tanst** [comment]
You can download it from https://synology.emby.media/packages/xpenology/stable/4.4.1.0-1/EmbyServer_4.4.1.0-1_xpenology.spk

**Comment by LukePulverenti** [comment]
They're available now.

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/88446-new-synology-package-for-testing/
