### ISSUE TITLE
Using the latest beta and it's not scraping from tvdb at all

### ISSUE THREAD

**Issue by NeverExists07** [MediaBrowser/Emby.Releases#52]
Missing all the artwork from tvdb plus it's not showing the special episodes with the season content for all the shows. Only some. after I made sure the box was checked. Also it's showing the same image for all the seasons instead of they're proper Covers.

**Comment by Happy2Play** [comment]
Please post in the forum and go over a specific example.  There is still a known issues with season images since TVDB api changed also.

**Comment by anoma** [comment]
https://forums.thetvdb.com/viewtopic.php?f=3&t=61687

TVDB is having a hard time of it today. Issues are widespread and probably not Emby specific

**Comment by NeverExists07** [comment]
It's still not showing any art from tvdb. I don't know how to make that any clearer lol. It works fine on the tvdb site just doesn't show up in emby. Just tmdb.

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/79269-tvdb-api-issues/?p=829957

**Comment by PartTheSeas** [comment]
I'm back on Emby for ~2 months and TVDB didn't fetch metadata not only for the last 6-16 hours, but eversince API v3 was released :/

**Comment by LukePulverenti** [comment]
Looks like some of the issues are beginning to clear up:
https://emby.media/community/index.php?/topic/79269-tvdb-api-issues/?p=830514

**Comment by LukePulverenti** [comment]
If you're still having an issue please provide an example and attach the emby server log. Thanks.
