### ISSUE TITLE
Live TV Guide Extremely Slow on Tizen

### ISSUE THREAD

**Issue by treynonymous** [MediaBrowser/Emby.Releases#53]
Hello,

I am using the Emby beta (1.0.71) on a Samsung UN55KU6290 television. The Live TV function does not work very well, and the program guide is essentially unusable due to its extremely slow speed to load, and when it does load it takes forever to scroll through just a few pages of channels.

Compared to my Roku (I think it is a 3100), it is night and day. The Roku version works just as fast, if not faster, than a cable/satellite/IPTV set-top box. 

Is this a case of the Live TV function needing more polish in the Tizen version, or a case that the TV (despite having a quad core processor) has considerably less processing power than the Roku?

**Comment by LukePulverenti** [comment]
Hi, this is resolved in newer versions of the app. Thanks.
