### ISSUE TITLE
QNAP + Emby 4.4.0.40 issue

### ISSUE THREAD

**Issue by tmysik** [MediaBrowser/Emby.Releases#55]
Hello,
I am using Emby on my QNAP device and it is working great. I have upgraded to version `4.4.0.40` and have an issue with it - I automatically turn off my QNAP every day at midnight and start it again at 6am. Emby used to work without any problem with such a setup. But this new version "does not start properly" (not sure what the real cause is) - in the morning, I can see it in my QNAP as running but the web interface is not (KODI cannot connect to it either). I have to stop it and start it again, then everything works as expected.

Sorry if this report belongs to some other Emby repository/project.

Thank you for your work, it is perfect!

**Comment by tmysik** [comment]
If you tell me how to help (to get logs or similarly), I will do it, of course.

**Comment by oonqt** [comment]
Github isn't very active, you should check out the [forums](https://emby.media/community) 

It would also be a good idea to attach a server log from when this happened on your forum thread

**Comment by tmysik** [comment]
@oonqt Thanks! Will try.

**Comment by LukePulverenti** [comment]
Closing as we're currently working together in the community.
