### ISSUE TITLE
RPM posttrans scriptlet generates error

### ISSUE THREAD

**Issue by Sir-Launcelot** [MediaBrowser/Emby.Releases#56]
Minor issue, but it doesn't change the settings you want it to.

Output of emby-server-rpm_4.5.0.8_x86_64.rpm %posttrans script:
    usermod: user 'emby:emby' does not exist

This line needs to be changed, as it only accepts a username.
`getent passwd emby > /dev/null 2>&1 && usermod -c 'Emby Server' -g emby -d /var/lib/emby -m -s /usr/bin/nologin emby:emby`

Corrected line:
`getent passwd emby > /dev/null 2>&1 && usermod -c 'Emby Server' -g emby -d /var/lib/emby -m -s /usr/bin/nologin emby`

**Comment by alucryd** [comment]
Thanks for the heads up, updated our spec file.

**Comment by LukePulverenti** [comment]
It's in our beta packages if you'd like to try it out. Thanks.

**Comment by LukePulverenti** [comment]
Hi, this is resolved in the latest version. Please let us know if you are still having an issue. Thanks !
