### ISSUE TITLE
4.4.3.0 release caused core dump and will not start

### ISSUE THREAD

**Issue by lolmc** [MediaBrowser/Emby.Releases#58]
Running on Linux Mint and I've done many upgrades without issue before. Was running 4.4.2.0 and upgraded to 4.4.3.0 but had core dump fault:
● emby-server.service - Emby Server is a personal media server with apps on just about every device.
   Loaded: loaded (/usr/lib/systemd/system/emby-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Tue 2020-06-02 18:57:04 BST; 2s ago
  Process: 4770 ExecStart=/opt/emby-server/bin/emby-server (code=dumped, signal=ABRT)
 Main PID: 4770 (code=dumped, signal=ABRT)

Jun 02 18:57:03 monster emby-server[4770]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
Jun 02 18:57:03 monster emby-server[4770]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
Jun 02 18:57:03 monster emby-server[4770]:    at Emby.Server.Implementations.Logging.FileLogger..ctor(String path)
Jun 02 18:57:03 monster emby-server[4770]:    at Emby.Server.Implementations.Logging.SimpleLogManager.ReloadLogger(LogSeve
Jun 02 18:57:03 monster emby-server[4770]:    --- End of inner exception stack trace ---
Jun 02 18:57:03 monster emby-server[4770]:    at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsT
Jun 02 18:57:03 monster emby-server[4770]:    at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
Jun 02 18:57:03 monster emby-server[4770]:    at EmbyServer.Program.Main(String[] args)
Jun 02 18:57:04 monster systemd[1]: emby-server.service: Main process exited, code=dumped, status=6/ABRT
Jun 02 18:57:04 monster systemd[1]: emby-server.service: Failed with result 'core-dump'.

Tried downgrading to 4.4.2.0 but same issue, also tried removing and installing 4.4.2.0 with the same result.

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/86953-4430-upgrade-release-caused-core-dump-and-will-not-start/
