### ISSUE TITLE
After Windows 10 update 2004, Emby Server not working

### ISSUE THREAD

**Issue by Zodler** [MediaBrowser/Emby.Releases#59]
Windows 10 just updated to the new version 2004. Now emby server not working.

When I launch emby server, it starts and I see the tray icon. But cannot access the server with
localhost:8096/web/index.html
or the exact address
192.168.1.100:8096/web/index.html

Also not accessible within iOS app.

**Comment by LukePulverenti** [comment]
Hi there, what happens when you try? Please attach the emby server log. thanks.

**Comment by LukePulverenti** [comment]
Let's help you here:
https://emby.media/community/index.php?/topic/87200-after-windows-10-update-2004-emby-server-not-working/
Thanks.
