### ISSUE TITLE
Cannot install on Synology DSM 7.0 Preview 

### ISSUE THREAD

**Issue by hetaoos** [MediaBrowser/Emby.Releases#66]
Details: 
https://help.synology.com/developer-guide/privilege/preface.html

[Download Center for DiskStation Manager 7.0 Preview](https://prerelease.synology.cn/en-global/download/dsm_preview/global)

**Some popular models of firmware**
- [DS1019+](https://global.download.synology.com/download/DSM/beta/7.0/40850/DSM_DS1819+_40850.pat)
- [DS918+](https://global.download.synology.com/download/DSM/beta/7.0/40850/DSM_DS918+_40850.pat)
- [DS916+](https://global.download.synology.com/download/DSM/beta/7.0/40850/DSM_DS916+_40850.pat)
- [VirtualDSM](https://global.download.synology.com/download/DSM/beta/7.0/40850/DSM_VirtualDSM_40850.pat)

**Comment by LukePulverenti** [comment]
Hi there, what happens when you try to install it?

**Comment by hetaoos** [comment]
Hi,

>Failed to install. The package should run with a [lower privilege level](https://help.synology.com/developer-guide/privilege/preface.html). Please contact the package 
developer to modify the privilege settings.


![aaa](https://user-images.githubusercontent.com/1094462/92590214-66cb3680-f2ce-11ea-84ea-d5fafd510627.png)
![bbb](https://user-images.githubusercontent.com/1094462/92590221-6af75400-f2ce-11ea-9e75-4d5181a9af56.png)

**Comment by matrixn** [comment]
same happens for the newly packages dedicated for DSM 7. I just tried to install (https://github.com/MediaBrowser/Emby.Releases/releases/download/4.6.0.2/emby-server-synology7_4.6.0.2_x86_64.spk) on DS1019+ with DSM 7 and i get the lower privilege level error too. I've also tried to remove the emby user and old emby shared forlder and tried again, no luck.

Any ideeas on how to get past this issue?

**Comment by hetaoos** [comment]
@matrixn 

I found a way to manually start the installed emby:
>/var/packages/EmbyServer/scripts/start-stop-status start

If you want to upgrade to a new version, you need to manually replace the files in `/volume1/@appstore/EmbyServer`

Of course, you can also consider using Emby in Docker.

**Comment by matrixn** [comment]
@hetaoos 
I assume you need to have it installed. I uninstalled my old emby instalation just after the dsm had updated. 
At the moment I am using it in docker at the moment and it feels a bit slowish...

**Comment by LukePulverenti** [comment]
We still have a little more work to do regarding DSM7. You can follow along here:
https://emby.media/community/index.php?/topic/89742-synology-dsm70-beta-emby
Thanks.

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/93185-synology-dsm-7-testing/
