### ISSUE TITLE
Can't work on contOS

### ISSUE THREAD

**Issue by raiots** [MediaBrowser/Emby.Releases#69]
System: CentOS 7 with bbr
Server: VPS that has a ipv4 address

Problem:

can not get into localhost:8096
by command lsof -i:8096 , I found the emby server is working, but listening by a ipv6 type. I do not have ipv6!

![image](https://user-images.githubusercontent.com/60507671/100539882-6a1cf100-3231-11eb-91d0-2e25b0c95a92.png)

**Comment by LukePulverenti** [comment]
https://github.com/MediaBrowser/Emby/issues/3656
